### ISSUE TITLE
fusionauth-app not starting after brew install

### ISSUE THREAD

**Issue by scopendo** [FusionAuth/homebrew-fusionauth#1]
I installed fusionauth-search and app using brew on Mac OS as on fusionauth.io home page.  The search appears to be running, the app however won't start.  The log shows:

```
/usr/local/Cellar/fusionauth-app/1.5.0/fusionauth-app/apache-tomcat/bin/setenv.sh: line 43: wget: command not found
tar: Error opening archive: Failed to open '/usr/local/Cellar/fusionauth-app/1.5.0/fusionauth-app/apache-tomcat/../../java/jre-macos-1.8.0+u171.tar.gz'
rm: ./jre-macos-1.8.0+u171.tar.gz: No such file or directory
```

Running `java -version` on my machine shows:

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by scopendo** [comment]
Note that after uninstalling the brew formulae and running the shell script, FusionAuth is now running okay, so it appears to be an issue with installing via brew.

**Comment by robotdan** [comment]
Thanks for reporting this @scopendo. I think our brew formula expects `wget` to be available. 

The work-around will be to install `wget` first, we may need to update our scripts to use `curl` instead since I think that will always be available. 

Or you can use the fast path install script as well. https://fusionauth.io/docs/v1/tech/installation-guide/fast-path

```
sh -c "curl -fsSL https://raw.githubusercontent.com/FusionAuth/fusionauth-install/master/install.sh | sh"
```

**Comment by scopendo** [comment]
Yep, the fast path install script works fine.
