### ISSUE TITLE
1.36.7 has a SHA256 mismatch

### ISSUE THREAD

**Issue by oottinger** [FusionAuth/homebrew-fusionauth#6]
Can't upgrade to the latest version due to a SHA256 mismatch.  This is specifically related to `fusionauth-app`, but I didn't try to get `fusionauth-search` to check.

```
Error: SHA256 mismatch
Expected: 34d5b7b83ba3f0eb754f8f713d179bf285d954d252cd7d2f84ccd83ab6ebbc31
  Actual: 96964305c57187bf7b2b699c714ce5a23eb5c27d2509b3be11877e4554041053
```

I'm trying to upgrade from 1.36.6

```
fusionauth/fusionauth/fusionauth-app 1.36.6 -> 1.36.7
fusionauth/fusionauth/fusionauth-search 1.36.6 -> 1.36.7
```

**Comment by mooreds** [comment]
Hmmm. I am not sure what is going on. We just use publish.sh to update the homebrew script and I looked at this and ran the sha command it runs manually and came up with the `969...` value you found, rather than the `34d...` value the script somehow has. 

I added a PR which updates those values: https://github.com/FusionAuth/homebrew-fusionauth/pull/7 . Will get someone to review this in the next week or so.

Sorry about that!
